### ISSUE TITLE
Getting error while npm install issue with node-sass

### ISSUE THREAD

**Issue by sairaj1412** [simpletut/React-Redux-Firebase-eCommerce-Website#41]
Node v16

npm ERR! code 1
npm ERR! path D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=        
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\my work\\local apps\\React-Redux-Firebase-eCommerce-Website-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.1.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:194:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\my work\\local apps\\React-Redux-Firebase-eCommerce-Website-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\my work\local apps\React-Redux-Firebase-eCommerce-Website-master\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.1.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

-

**Comment by pak11273** [comment]
You need to use python version 2.7 and place it in your ENV path too.

**Comment by Saurav-SayOne** [comment]
> You need to use python version 2.7 and place it in your ENV path too.

hlo how do we place it in env path

**Comment by atharva-k-pccoe** [comment]
you can also force npm using --force
